import Link from "next/link";
import TLDRBadge from "@/app/components/TLDRBadge";
import PostTags from "@/app/components/PostTags";
import RelatedPosts from "@/app/components/RelatedPosts";

export const metadata = {
  title: "How I Built an AI Content Pipeline — Jose and Goose",
  description: "Using Claude Haiku for topic tags, Supabase vector embeddings for related posts, and build-time scripts to turn 18 blog posts into a connected content product",
};

export default function HowIBuiltContentPipeline() {
  return (
    <article className="post">
      <div className="post-back">
        <Link href="/writing">← All Writing</Link>
      </div>

      <div className="post-meta">
        <span>April 4, 2026</span>
        <span className="post-meta-dot">&middot;</span>
        <span>7 min read</span>
      </div>
      <PostTags slug="how-i-built-content-pipeline" />

      <h1 className="post-title">How I Built an AI Content Pipeline for Every Writing Post</h1>
      <p className="post-subtitle">
        Using Claude Haiku for topic tags, Supabase vector embeddings for related posts, and build-time scripts to turn 18 blog posts into a connected content product
      </p>

      <div className="post-body">
        <div className="post-recipe-meta">
          <div className="post-recipe-row">
            <span className="post-recipe-label">Yield</span>
            <span>AI-generated tags on all posts, 2 related post suggestions per page, verified reading times, dynamic tag filtering</span>
          </div>
          <div className="post-recipe-row">
            <span className="post-recipe-label">Difficulty</span>
            <span>2 / 5 &mdash; three scripts, two components, one CSS block</span>
          </div>
          <div className="post-recipe-row">
            <span className="post-recipe-label">Total Cook Time</span>
            <span>~1 hour in one session</span>
          </div>
        </div>
        <TLDRBadge slug="how-i-built-content-pipeline" />

        {/* ── INGREDIENTS ── */}
        <h2>Ingredients</h2>
        <ul>
          <li>
            <strong><a href="https://claude.ai/download" target="_blank" rel="noopener noreferrer">Claude Code</a></strong>{" "}
            &mdash; terminal-based AI for building scripts and components <em>($200/yr)</em>
          </li>
          <li>
            <strong><a href="https://www.anthropic.com/api" target="_blank" rel="noopener noreferrer">Claude API &mdash; Haiku model</a></strong>{" "}
            &mdash; for generating topic tags per post <em>(own API key, pay-per-use)</em>
          </li>
          <li>
            <strong><a href="https://supabase.com" target="_blank" rel="noopener noreferrer">Supabase</a></strong>{" "}
            &mdash; pgvector embeddings for semantic similarity <em>(free tier)</em>
          </li>
          <li>
            <strong><a href="https://nextjs.org" target="_blank" rel="noopener noreferrer">Next.js</a></strong>{" "}
            &mdash; the framework running the site <em>(free)</em>
          </li>
          <li>
            <strong><a href="https://vercel.com" target="_blank" rel="noopener noreferrer">Vercel</a></strong>{" "}
            &mdash; hosting and deployment <em>(free)</em>
          </li>
        </ul>

        {/* ── THE PROBLEM ── */}
        <h2>What I Was Trying to Solve</h2>
        <p>
          After 18 posts, the Writing section was a flat list. Every post had a title, a subtitle,
          and a date. Five manual tags &mdash; Website, Features, Automation, Headless Linux, Games &mdash;
          were the only way to filter. No related posts. No way to discover connections between builds.
          If you finished reading about the market briefing bot, there was nothing pointing you toward
          the Garmin automation that uses the same architecture.
        </p>
        <p>
          I wanted three things: richer topic tags generated by AI from a proper taxonomy, related post
          suggestions based on actual content similarity, and verified reading times. All static.
          All generated at build time. All following the same pattern I&rsquo;d already established
          with <Link href="/writing/how-i-built-tldr">TL;DR by Goose</Link>.
        </p>

        {/* ── THE FOUNDATION ── */}
        <h2>The Foundation That Already Existed</h2>
        <p>
          This build didn&rsquo;t start from zero. Two earlier projects laid the groundwork:
        </p>
        <ul>
          <li>
            <strong><Link href="/writing/how-i-built-tldr">TL;DR by Goose (March 5)</Link></strong> &mdash; established the pattern: a TypeScript script
            reads post content, calls Claude Haiku, writes results to a static JSON file, and a React
            component reads from that JSON at render time. Zero runtime API calls.
          </li>
          <li>
            <strong><Link href="/writing/how-i-upgraded-search-to-vectors">Vector Embeddings (April 4)</Link></strong> &mdash; every post already had a semantic
            embedding stored in Supabase via <code>generate-embeddings.ts</code>. These embeddings
            power the site&rsquo;s vector search. I just needed to query them differently.
          </li>
        </ul>
        <p>
          The architecture decision was already made. I just needed to follow it.
        </p>

        {/* ── THE BUILD ── */}
        <h2>The Build</h2>
        <p className="post-session-meta">Afternoon, April 4 &mdash; ~1 hour</p>

        <h3>Part 1: AI Tag Generation</h3>
        <p>
          I built <code>scripts/generate-tags.ts</code> following the exact same pattern as the TL;DR
          script. It reads each post&rsquo;s JSX file, strips the markup to extract prose, and sends
          the content to Claude Haiku with a fixed taxonomy of 11 tags:
        </p>
        <p>
          <em>AI Tools, Backend, Frontend, Automation, Product Thinking, Game Dev, Data, DevOps,
          Security, API Design, Linux</em>
        </p>
        <p>
          Haiku picks 3&ndash;5 per post. The prompt is strict: return only a JSON array of strings
          from the approved list. No explanations, no creativity. The model is a classifier here,
          not a writer.
        </p>

        <div className="post-visual">
          <div className="post-terminal">
            <div className="post-terminal-bar">
              <span className="post-terminal-dot post-terminal-dot--red"></span>
              <span className="post-terminal-dot post-terminal-dot--yellow"></span>
              <span className="post-terminal-dot post-terminal-dot--green"></span>
              <span className="post-terminal-bar-title">Terminal</span>
            </div>
            <div className="post-terminal-body">
              <div>
                <span className="post-terminal-prompt">user@MacBook-Air</span>{" "}
                joseandgoose-site-main % <span className="post-terminal-cmd">npx tsx scripts/generate-tags.ts --all</span>
              </div>
              <div className="post-terminal-dim">Generating tags for 18 posts...</div>
              <br />
              <div><span className="post-terminal-success">&check;</span> how-i-upgraded-search-to-vectors: [Backend, AI Tools, Data]</div>
              <div><span className="post-terminal-success">&check;</span> how-i-built-api-server: [Backend, API Design, Linux, Security, DevOps]</div>
              <div><span className="post-terminal-success">&check;</span> how-i-built-cron-ops: [Linux, Automation, DevOps]</div>
              <div><span className="post-terminal-success">&check;</span> how-i-built-numerator: [AI Tools, Frontend, Game Dev]</div>
              <div className="post-terminal-dim">... 14 more posts</div>
              <br />
              <div className="post-terminal-dim">Done.</div>
            </div>
          </div>
          <p className="post-visual-caption">
            18 posts tagged in under a minute. Results saved to <code>app/lib/tags.json</code>.
          </p>
        </div>

        <p>
          The script also counts words in each post and computes a reading time at 230 words per minute.
          The original reading times were manually estimated &mdash; some were close, some were off by
          a few minutes. The automated counts replaced all of them.
        </p>

        <h4 className="post-dev-heading">🔧 Developer section: tag generation</h4>
        <ul>
          <li>Script follows the <code>generate-tldr.ts</code> pattern: manual <code>.env.local</code> parsing, JSX stripping via regex, Claude Haiku API call</li>
          <li>First run had 6 failures &mdash; Haiku wrapped JSON output in markdown code fences (<code>```json ... ```</code>). Fixed by stripping fences before <code>JSON.parse</code></li>
          <li>Tags are validated against the taxonomy after parsing &mdash; any hallucinated tags are filtered out</li>
          <li>Output is <code>app/lib/tags.json</code> keyed by slug, containing tags array, word count, and computed reading time</li>
          <li>Reading time uses the full stripped text (not truncated), while the Haiku prompt gets the first 4,000 characters</li>
        </ul>

        <h3>Part 2: Related Posts via Vector Similarity</h3>
        <p>
          The site already had semantic embeddings for every post stored in Supabase, generated by
          the <code>generate-embeddings.ts</code> script from the vector search build. Those embeddings
          use the MiniLM-L6-v2 model &mdash; each post is represented as a 384-dimensional vector
          based on its title, description, and TL;DR summary.
        </p>
        <p>
          I built <code>scripts/generate-related.ts</code> to query all post embeddings from Supabase,
          compute cosine similarity between every pair, and pick the top 2 most similar posts for each.
          The results are written to <code>app/lib/related.json</code> &mdash; same static JSON pattern
          as everything else.
        </p>
        <p>
          The similarity scores make intuitive sense. The cron ops post is most related to the server
          alerts post (0.600). The market daily briefing maps to the Garmin recaps (0.532) &mdash; both
          are automated email pipelines on the Alienware. The Gemini Grades post maps to the original
          site build post (0.675) &mdash; they&rsquo;re literally about the same project.
        </p>

        <h4 className="post-dev-heading">🔧 Developer section: related posts</h4>
        <ul>
          <li>Embeddings are stored as JSON strings in Supabase &mdash; script parses them to <code>number[]</code> arrays before computing similarity</li>
          <li>Cosine similarity is computed in pure TypeScript (dot product / product of magnitudes) &mdash; no external math library</li>
          <li>Output is <code>app/lib/related.json</code> keyed by slug, each value is an array of 2 objects with <code>slug</code> and <code>title</code></li>
          <li>The script filters to <code>content_type = &apos;post&apos;</code> only &mdash; static pages and features are excluded from related suggestions</li>
        </ul>

        <h3>Part 3: The UI Components</h3>
        <p>
          Two new components, both following the TLDRBadge pattern: client components that read from
          static JSON, no API calls, no loading states.
        </p>
        <p>
          <strong>PostTags</strong> renders tag pills below the post meta (date and read time).
          Each pill is a small rounded badge in the site&rsquo;s forest-green-on-pale-green color scheme.
          The tags come directly from the post metadata in <code>posts.ts</code>.
        </p>
        <p>
          <strong>RelatedPosts</strong> appears at the bottom of each post, above the back navigation.
          Two cards with the related post&rsquo;s title and reading time, styled as bordered links
          that highlight on hover. It reads from <code>related.json</code> and cross-references{" "}
          <code>posts.ts</code> for the reading time.
        </p>
        <p>
          The Writing index page also got an upgrade: the tag filter pills are now derived dynamically
          from the posts array instead of being hardcoded. Adding a new tag to any post automatically
          adds it to the filter bar &mdash; no manual list to maintain.
        </p>

        <h4 className="post-dev-heading">🔧 Developer section: components</h4>
        <ul>
          <li>Both components are <code>&quot;use client&quot;</code> &mdash; <code>PostTags</code> because it imports from the posts module, <code>RelatedPosts</code> because it reads static JSON</li>
          <li><code>WritingFilter.tsx</code> derives tags with <code>Array.from(new Set(posts.flatMap(p =&gt; p.tags))).sort()</code> &mdash; deduped and alphabetized</li>
          <li>All 18 post pages were updated programmatically via a Node script that added imports, inserted <code>&lt;PostTags&gt;</code> after <code>.post-meta</code>, and <code>&lt;RelatedPosts&gt;</code> before <code>.post-back--bottom</code></li>
          <li>CSS uses existing design tokens: <code>--forest-pale</code> backgrounds, <code>--forest</code> text for tags, <code>--rule</code> borders for related post cards</li>
        </ul>

        {/* ── THE PIPELINE ── */}
        <h2>The Full Pipeline</h2>
        <p>
          Here&rsquo;s what the content pipeline looks like now, from writing a post to deploying it:
        </p>
        <ol>
          <li>Write the post as a TSX file in <code>app/writing/[slug]/page.tsx</code></li>
          <li>Add metadata to <code>app/lib/posts.ts</code></li>
          <li>Run <code>npx tsx scripts/generate-tldr.ts [slug]</code> &mdash; AI summary</li>
          <li>Run <code>npx tsx scripts/generate-tags.ts [slug]</code> &mdash; AI topic tags + reading time</li>
          <li>Run <code>npx tsx scripts/generate-embeddings.ts</code> &mdash; vector embeddings</li>
          <li>Run <code>npx tsx scripts/generate-related.ts</code> &mdash; related post suggestions</li>
          <li>Deploy with <code>vercel --prod</code></li>
        </ol>
        <p>
          Steps 3&ndash;6 are all build-time, all idempotent, all writing to static JSON or Supabase.
          The live site never touches an API at read time. Every piece of AI-generated content is
          baked into the build.
        </p>

        {/* ── WHAT THIS UNLOCKS ── */}
        <h2>What This Unlocks</h2>
        <p>
          The Writing section went from a flat blog to a connected content product. Readers can
          filter by 11 topic tags, see related posts at the bottom of every article, and get
          accurate reading times. Every post is now enriched with AI-generated metadata that
          would have taken hours to create manually.
        </p>
        <p>
          More importantly: all of this data &mdash; the TL;DR summaries, the topic tags, the
          vector embeddings, the related post graph &mdash; feeds directly into Ask Goose, the
          conversational AI assistant coming to the site. When Ask Goose answers a question about
          what I&rsquo;ve built, it won&rsquo;t be searching raw text. It&rsquo;ll be retrieving
          semantically similar content from a curated, tagged, summarized knowledge base.
        </p>
        <p>
          The content pipeline isn&rsquo;t just a feature. It&rsquo;s the retrieval layer for
          everything that comes next.
        </p>
      </div>
      <RelatedPosts slug="how-i-built-content-pipeline" />

      <div className="post-back post-back--bottom">
        <Link href="/writing">← Back to all writing</Link>
      </div>
    </article>
  );
}
