import Link from "next/link";
import TLDRBadge from "@/app/components/TLDRBadge";
import PostTags from "@/app/components/PostTags";
import RelatedPosts from "@/app/components/RelatedPosts";

export const metadata = {
  title: "How I Built a Market Briefing That Writes and Sends Itself Every Morning — Jose and Goose",
  description: "Building a daily AI-generated market email with Claude, Resend, Supabase subscribers, and a headless Linux server — from data scraping to inbox delivery",
};

export default function HowIBuiltMarketDaily() {
  return (
    <article className="post">
      <div className="post-back">
        <Link href="/writing">← All Writing</Link>
      </div>

      <div className="post-meta">
        <span>March 17, 2026</span>
        <span className="post-meta-dot">·</span>
        <span>9 min read</span>
      </div>
      <PostTags slug="how-i-built-market-daily" />

      <h1 className="post-title">How I Built a Market Briefing That Writes and Sends Itself Every Morning</h1>
      <p className="post-subtitle">
        A Python script on a headless Linux server scrapes market data, asks Claude to explain why markets moved, formats an HTML email with options chains and news, and delivers it to subscribers via Resend — every weekday at 8am with zero manual input
      </p>

      <div className="post-body">

        {/* ── Recipe Card ── */}
        <div className="post-recipe-meta">
          <div className="post-recipe-row">
            <span className="post-recipe-label">Yield</span>
            <span>A daily market briefing email that writes itself — market snapshot, AI-generated thesis, news bullets, economic calendar, and options chains, delivered to subscribers every weekday morning</span>
          </div>
          <div className="post-recipe-row">
            <span className="post-recipe-label">Difficulty</span>
            <span>Intermediate (Python data scraping, Claude API, Resend email delivery, Supabase subscriber management, cron scheduling)</span>
          </div>
          <div className="post-recipe-row">
            <span className="post-recipe-label">Total Cook Time</span>
            <span>~8 hours across 6 sessions over 20 days — from first prototype to v0.3.0 with full subscriber management</span>
          </div>
        </div>
        <TLDRBadge slug="how-i-built-market-daily" />

        {/* ── Ingredients ── */}
        <h2>Ingredients</h2>
        <ul>
          <li>
            <strong>Headless Linux server</strong>{" "}
            — the always-on Alienware from the earlier posts, running the 8am cron job <em>(already set up)</em>
          </li>
          <li>
            <strong>Python 3</strong>{" "}
            — main script language for scraping, parsing, and formatting <em>(free)</em>
          </li>
          <li>
            <strong>Claude API (Haiku)</strong>{" "}
            — generates the &ldquo;why markets moved&rdquo; thesis from raw data <em>(~$0.01/day)</em>
          </li>
          <li>
            <strong><a href="https://resend.com" target="_blank" rel="noopener noreferrer">Resend</a></strong>{" "}
            — email delivery from a custom domain <em>(free tier: 3,000 emails/month)</em>
          </li>
          <li>
            <strong><a href="https://supabase.com" target="_blank" rel="noopener noreferrer">Supabase</a></strong>{" "}
            — subscriber list with token-based unsubscribe <em>(free tier)</em>
          </li>
          <li>
            <strong>Schwab Market Data API</strong>{" "}
            — real-time SPX and stock options chains <em>(free with brokerage account)</em>
          </li>
        </ul>

        {/* ── The Problem ── */}
        <h2>The Problem: Morning Market Noise</h2>
        <p>
          Every morning I&rsquo;d open three tabs — Yahoo Finance, CNBC, and a brokerage app — skim
          headlines, try to figure out why futures were up or down, and check if anything was happening
          with positions I cared about. It took 15&ndash;20 minutes and most of it was noise. I
          didn&rsquo;t need more data. I needed someone to tell me what happened, why, and what to
          watch — in one page, in my inbox, before I finished coffee.
        </p>

        <p>
          So I built the someone.
        </p>

        {/* ── What the Email Contains ── */}
        <h2>What Lands in the Inbox</h2>
        <p>
          Every weekday at 8am ET, subscribers get an HTML email with these sections:
        </p>

        <ul>
          <li><strong>Market snapshot</strong> — a compact table of S&amp;P 500, Nasdaq, Dow, VIX, 10Y yield, Bitcoin, and oil with daily change percentages</li>
          <li><strong>&ldquo;Why markets moved&rdquo;</strong> — a one-sentence thesis generated by Claude Haiku from the raw data. Not a summary of headlines — a synthesis of <em>why</em> the numbers moved the way they did.</li>
          <li><strong>Top market news</strong> — same-day headlines only, filtered by publication date so nothing stale leaks in</li>
          <li><strong>Political &amp; macro bullets</strong> — policy moves, Fed signals, anything that could move markets this week</li>
          <li><strong>Delivery platforms</strong> — news specific to companies I track (only shown when there&rsquo;s actual news; omitted entirely when there isn&rsquo;t)</li>
          <li><strong>Economic calendar</strong> — upcoming data releases and Fed events</li>
          <li><strong>SPX options chain</strong> — 10 nearest ATM calls and puts, collapsed in a <code>&lt;details&gt;</code> tag</li>
          <li><strong>Stock options</strong> — covered call candidates for positions I hold, two nearest Friday expirations</li>
        </ul>

        <div className="post-tip">
          <span className="post-tip-label">The thesis is the whole point</span>
          <p>
            The market snapshot is data I can get anywhere. The news bullets are aggregation. But the
            one-sentence &ldquo;why markets moved&rdquo; thesis — that&rsquo;s Claude reading the full
            picture and producing a take. It&rsquo;s wrong sometimes. But it&rsquo;s a starting point
            for thinking, not a source of truth, and that&rsquo;s exactly what I wanted.
          </p>
        </div>

        {/* ── How It Works ── */}
        <h2>How the Script Runs</h2>
        <p>
          One Python script. One cron job (a scheduled task that Linux runs automatically at a set
          time). No web framework, no queue, no Lambda function. The script runs top-to-bottom
          every weekday morning:
        </p>

        <h4 className="post-dev-heading">&#x1f527; Developer section: Execution flow</h4>
        <ul>
          <li>Cron fires at 8am ET: <code>0 8 * * 1-5</code></li>
          <li>Script fetches market data from multiple sources (Schwab API for options, web scraping for news and calendar)</li>
          <li>Raw data is passed to Claude Haiku API with a prompt: &ldquo;Given this market data, write one sentence explaining why markets moved today&rdquo;</li>
          <li>Claude returns the thesis, which is parsed and inserted into the HTML email template</li>
          <li>News bullets are filtered to same-day only using publication dates from RSS feeds (structured data feeds that news sites publish — like a machine-readable version of their headlines page)</li>
          <li>Options chains are fetched from Schwab Market Data API — 10 strikes near the current price for SPX, plus covered call candidates</li>
          <li>Full HTML email is assembled and sent via Resend API to each active subscriber</li>
        </ul>

        {/* ── Subscriber Management ── */}
        <h2>Subscribers Without a Backend</h2>
        <p>
          I didn&rsquo;t want to build a user system. No passwords, no accounts, no login page.
          The subscriber flow is two API routes on the joseandgoose.com Next.js site and one
          Supabase table:
        </p>

        <h4 className="post-dev-heading">&#x1f527; Developer section: Subscriber system</h4>
        <ul>
          <li><code>market_subscribers</code> table in Supabase — email, unique unsubscribe token, active flag, timestamps</li>
          <li><code>/api/market-subscribe</code> — POST with email, creates a row with a UUID token</li>
          <li><code>/api/market-unsubscribe?token=...</code> — GET with token, marks the subscriber as inactive</li>
          <li>Every email footer includes a personalized unsubscribe link using the subscriber&rsquo;s token</li>
          <li>Daily dedup: the script stamps <code>last_sent_date</code> after each successful send — if cron fires twice, nobody gets a duplicate</li>
          <li>Rate limiting: 0.6 second delay between sends to stay under Resend&rsquo;s 2 req/sec limit</li>
        </ul>

        <p>
          The <code>--test</code> flag bypasses the subscriber list and sends only to my personal
          email. I use this every time I change the template or add a new section. When it looks
          right in my inbox, I push the change and cron handles the rest.
        </p>

        {/* ── Custom Domain ── */}
        <h2>Sending from a Real Domain</h2>
        <p>
          Emails from <code>market@joseandgoose.com</code> instead of a generic Resend address.
          This required DNS verification — adding special records to the domain&rsquo;s DNS
          settings (DKIM and SPF — basically proof to email providers that you own the domain
          and are allowed to send from it). Once verified, every email passes spam filters and lands
          in the primary inbox, not promotions or junk.
        </p>

        <p>
          The domain verification took 10 minutes. The result is permanent: every Resend email
          from this domain now sends with full authentication. This is the same domain setup
          that powers the server alert emails from the earlier posts.
        </p>

        {/* ── The Details Tag Problem ── */}
        <h2>The Gmail Problem</h2>
        <p>
          Options chains are 20+ rows of data. Most subscribers don&rsquo;t want to scroll past
          them every morning. The solution: wrap them in <code>&lt;details&gt;</code> tags so
          they&rsquo;re collapsed by default and expandable on click.
        </p>

        <p>
          This works perfectly in Apple Mail. In Gmail, <code>&lt;details&gt;</code> tags are
          completely ignored — the content renders fully expanded, always. There&rsquo;s no fix.
          Gmail strips or ignores the tag. The workaround is keeping the options tables short
          (10 rows max) so even when expanded, they don&rsquo;t dominate the email.
        </p>

        <div className="post-tip">
          <span className="post-tip-label">HTML email is a time machine</span>
          <p>
            HTML email rendering is stuck in 2005. No flexbox, no grid, inconsistent
            <code>&lt;details&gt;</code> support, and every client has different quirks. If you&rsquo;re
            building HTML emails, test in Apple Mail, Gmail, and Outlook. What works in one will
            break in another.
          </p>
        </div>

        {/* ── Evolution ── */}
        <h2>How It Grew: v0.1 to v0.3</h2>
        <p>
          The first version was a single-file script that scraped Yahoo Finance and sent a basic
          text email to myself. Over 20 days and 6 sessions, it became something different:
        </p>

        <ul>
          <li><strong>v0.1</strong> — basic market snapshot + news bullets, sent to one email address</li>
          <li><strong>v0.2</strong> — added Claude Haiku thesis generation, SPX options chain via Schwab API, subscriber list from Supabase</li>
          <li><strong>v0.3</strong> — modularized into a package, added CNBC parsing with retry logic, degradation alerts when a data source fails, covered call candidates for held positions</li>
        </ul>

        <p>
          The modularization in v0.3 was the biggest single change. The original script was 400+
          lines in one file. Breaking it into modules (data fetching, AI synthesis, email assembly,
          subscriber management) made it possible to test and update individual sections without
          risking the whole pipeline.
        </p>

        {/* ── Final Output ── */}
        <h2>Final Output</h2>

        <p>
          The email has sent every weekday morning since mid-March. When a data source is down,
          the email still sends — with a degradation note in the affected section instead of
          crashing the whole pipeline. When everything works, the email is waiting in my inbox
          before Goose and I are done with the morning walk.
        </p>

        <h3>What went fast</h3>
        <ul>
          <li>
            <strong>Resend integration</strong> — already proven from the server alert emails. Same
            API key, same pattern. The custom domain was already verified. Adding a new sender
            took 5 minutes.
          </li>
          <li>
            <strong>Claude Haiku thesis</strong> — one API call with a clear prompt. The response
            is consistently one sentence, consistently useful as a starting point. Haiku is fast
            and cheap enough to run daily without thinking about cost.
          </li>
          <li>
            <strong>Subscriber table</strong> — Supabase table with 6 columns. The subscribe/unsubscribe
            API routes on the Next.js site were 30 lines each. Token-based unsubscribe means no
            auth system needed.
          </li>
        </ul>

        <h3>What needed patience</h3>
        <ul>
          <li>
            <strong>News freshness filtering</strong> — RSS feeds include items from the past week.
            Filtering to same-day-only required parsing <code>pubDate</code> and comparing against
            the current date in the right timezone. Early versions occasionally included yesterday&rsquo;s
            news, which defeated the purpose.
          </li>
          <li>
            <strong>CNBC parsing</strong> — the feed format changed once during development, breaking
            the bullet parser. Added retry logic and a fallback that detects both dash, asterisk, and
            bullet dot characters. Content parsing on the open web is inherently fragile.
          </li>
          <li>
            <strong>Options chain formatting</strong> — fitting a 10-column options table into an email
            that&rsquo;s readable on mobile required <code>white-space: nowrap</code>, a 13px font size,
            and cutting columns to only what matters (strike, bid, ask, IV, delta). The first version
            had 15 columns and was unreadable on anything smaller than a laptop.
          </li>
          <li>
            <strong>Schwab token management</strong> — the Schwab API uses OAuth tokens (temporary
            passwords that expire and need to be refreshed periodically). The token manager
            auto-rotates and saves new tokens, but getting the refresh flow right took a few rounds
            of debugging — especially when multiple scripts on the server share the same token file.
          </li>
        </ul>

        <p>
          The best part of this project isn&rsquo;t the code — it&rsquo;s the morning. I wake up,
          open my email, and the market brief is already there. No tabs to open, no apps to check,
          no 15 minutes of skimming. One email, one thesis, done.
        </p>
      <RelatedPosts slug="how-i-built-market-daily" />

        <div className="post-back post-back--bottom">
          <Link href="/writing">← Back to all writing</Link>
        </div>
      </div>
    </article>
  );
}
